# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d092c75bbb52445fde51f0f631886566415cd37aa585b685e0cd3f031ebff050a95de4160653ef358496e29c94cbbcb8c1ea1683e07a1667abb294c35eb3c01b

test:
  secret_key_base: 421e1d8850b9f5363b91fa537f4401b26a65e301331faf522e2c06fbf58873d5909749afad15ed4ecfdccd82589e6570d98faa820abd2a0d7221b9fd369f2bf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
